# Uncomment this line to define a global platform for your project
# platform :ios, "6.0"

target "WhatFor" do

end

target "WhatForTests" do

end

target "Acceptance Tests", :exclusive => true do
  pod 'KIF', '~>3.0' 
end
